CREATE TABLE routes (
    id UUID PRIMARY KEY,
    origin_name VARCHAR(255) NOT NULL,
    origin_street VARCHAR(255) NOT NULL,
    origin_city VARCHAR(100) NOT NULL,
    origin_state VARCHAR(100) NOT NULL,
    origin_country VARCHAR(100) NOT NULL,
    origin_postal_code VARCHAR(20),
    origin_lat FLOAT,
    origin_lng FLOAT,
    destination_name VARCHAR(255) NOT NULL,
    destination_street VARCHAR(255) NOT NULL,
    destination_city VARCHAR(100) NOT NULL,
    destination_state VARCHAR(100) NOT NULL,
    destination_country VARCHAR(100) NOT NULL,
    destination_postal_code VARCHAR(20),
    destination_lat FLOAT,
    destination_lng FLOAT,
    estimated_time INT NOT NULL,
    distance_km FLOAT NOT NULL,
    assigned_carrier_id UUID REFERENCES carriers(id) ON DELETE SET NULL,
    assigned_vehicle_id UUID REFERENCES vehicles(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);