CREATE TABLE shipping_orders (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    assigned_route_id UUID REFERENCES routes(id),
    assigned_carrier_id UUID REFERENCES carriers(id),
    assigned_vehicle_id UUID REFERENCES vehicles(id),
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(13),
    street VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20),
    lat FLOAT,
    lng FLOAT,
    status VARCHAR(50) NOT NULL DEFAULT 'En espera',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);